# ORM config
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
quarkus.flyway.migrate-at-start=true

# Quarkus general config
quarkus.http.port=${BACKEND_PORT}
quarkus.log.level=INFO
quarkus.log.category."io.quarkus".level=INFO

# Http Server config
quarkus.http.cors=true
quarkus.http.cors.origins=${CORS_ORIGINS:http://localhost:5173}
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization
quarkus.http.cors.exposed-headers=Content-Type,Authorization
quarkus.http.cors.access-control-allow-credentials=true

# JWT config
mp.jwt.verify.issuer=${JWT_ISSUER:http://localhost:5173}
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem

# INFRASTRUCTURE (S3, PostgreSQL)

# Postgres config
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}

# S3 config
r2.account-id=${R2_ACCOUNT_ID}
r2.access-key=${R2_ACCESS_KEY}
r2.secret-key=${R2_SECRET_KEY}
r2.bucket=${R2_BUCKET}
r2.public-url=${R2_PUBLIC_URL}
quarkus.s3.aws.region=auto

# INTEGRATIONS config (Strava)
strava.client-id=${STRAVA_CLIENT_ID}
strava.client-secret=${STRAVA_CLIENT_SECRET}
strava.redirect-uri=${STRAVA_REDIRECT_URI}